Added: ffmuc-eol-ssid package
freifunkMUC/site-ffm pull request #117
Opened 2021-06-14 19:35 UTC by GoliathLabs

I've added the ffmuc-eol-ssid package to the site.mk as well as to the genpkglist script.

Cheers 😄

2021-06-14 19:36 UTC, wolli80 approved these changes

2021-06-14 19:38 UTC, wolli80 reviewed
As diskussed need be approved by more peoople.

2021-06-14 19:47 UTC, goligo reviewed
I don't think this is a good idea - these "tiny" devices provide a majority of our nodes.

2021-06-14 19:54 UTC, GoliathLabs commented
In the long run, the devices will fall out of the Gluon upstream and it will be more difficult for us to provide them with updates. OpenWrt has already cancelled the updates because the devices are not in the new ath79 target. Gluon will drop the devices in the next release
In addition, the devices will continue to work, but they will also broadcast the message that they are EOL, especially because of the hardware restrictions (under a separate SSID). The original SSID with muenchen.freifunk.net/segment remains the same

2021-06-14 20:11 UTC, krombel requested changes, later dismissed
Dependencies not available yet.

2021-07-24 17:19 UTC, goligo commented
The devices important for us, namely TL-WR841N v9, v10 and v11, are supported in OpenWrt 21.02, in target ath79.tiny. However it is unlikely we will be able to provide a firmware image due to limited available flash, see https://github.com/goligo/site-ffm/tree/next841 .

2021-07-25 17:24 UTC, awlx commented
@GoliathLabs please resolve the merge conflict. Also we should really look into a more general and "non-biased" SSID like "wichtig.ffmuc.net" or "info.ffmuc.net"

2021-08-19 14:30 UTC, grische commented
@GoliathLabs can you rebase this, so we can get some CI sample builds for this PR?

2021-08-19 19:01 UTC, GoliathLabs commented
@grische Currently building the new firmware :)

2021-10-12 20:22 UTC, grische commented
> Dependencies not available yet.

I rebased this on top of the current stable and also (temporarily) bumped gluon-packages to include freifunkMUC/gluon-packages#19 to see if it builds at all.

2021-10-21 22:13 UTC, goligo commented
```
ERROR: please fix feeds/ffmuc/ffmuc-eol-ssid/Makefile - see logs/feeds/ffmuc/ffmuc-eol-ssid/dump.txt for details
```
```
Makefile:15: *** Package/ffmuc-eol-ssid is missing the TITLE field.  Stop.
```

2021-10-21 22:47 UTC, grische commented
Rebased on stable and updated PR to include the most recent patch of  freifunkMUC/gluon-packages#19

2021-10-23 11:27 UTC, goligo commented
```
/usr/bin/gluon-reconfigure: line 9: ./950-ffmuc-update-nagger: Permission denied
```
```
root@ffmuc-c46e1fae23a6:/lib/gluon/upgrade# ls -la
[...]
-rwxr-xr-x    1 root     root           808 Jul 28 14:17 820-dns-config
-rwxr-xr-x    1 root     root            36 Jul 28 14:17 900-remove-aptimer-config
-rw-r--r--    1 root     root           338 Jul 28 14:17 950-ffmuc-update-nagger
-rwxr-xr-x    1 root     root            74 Jul 28 14:17 998-commit
-rwxr-xr-x    1 root     root           139 Jul 28 14:17 999-version
```

2021-10-24 14:48 UTC, grische commented
As the dependent PR freifunkMUC/gluon-packages#19 has been merged, based the PR again on the freifunkMUC/gluon-packages.

@krombel that should address your comment

EDIT:
Once it finished, new images can be found here: https://github.com/freifunkMUC/site-ffm/actions/runs/1378040237

2021-10-25 06:05 UTC, goligo approved these changes
Finally builds successfully and also works as expected.

2021-10-25 10:51 UTC, merged