Do not cut git describe in custom release builds
freifunkMUC/site-ffm pull request #146
Opened 2021-09-01 18:26 UTC by grische

Currently if autoupdate is enabled on a custom next build, it will
automatically downgrade to the latest release. This change will use
the full git-describe name to avoid those downgrades.

Exemplatory tag name:
One commit on top of latest release "v2021.8.1"

Before: v2021.8.1~exp2021083100
After:  v2021.8.1-1-g2f13e5e~exp20210831

2021-09-01 20:28 UTC, krombel reviewed
"backport" of #145 but as next will be merged into stable in future either way I would not merge it in general (as it will cause merge conflicts later on)

2021-09-02 21:35 UTC, goligo approved these changes

2021-09-02 22:20 UTC, awlx requested changes
Could you reopen the PR with branch next as base? Otherwise as soon as we merge next with stable this will cause a conflict.

2021-09-03 11:18 UTC, grische commented
@awlx this has been merged to next as part of #145 already. I opened this PR as the commit in #145 will not apply cleanly because next used `...~next...`  before while stable always had `...~exp...` in the release name.

2021-09-03 17:20 UTC, goligo commented
Honestly, I don't see an issue with merging, there is hardly any code in site-ffm.

2021-09-03 17:26 UTC, awlx commented
Why can't we just cherry-pick that from next? It's the same and because of the same ref won't cause issues in the future.

2021-09-10 19:30 UTC, awlx approved these changes

2021-09-10 19:31 UTC, merged