Added: FFA domain
freifunkMUC/site-ffm pull request #151
Opened 2021-10-16 14:30 UTC by GoliathLabs

Good day,
I have added the FFA domain to our site config. Since I'm still planning some projects over in Augsburg and the FFA community is not really active anymore, I would like to get FFA up and running again with the support of Freifunk Munich.

Steps needed:
- [x] Allocate IP ranges in Netbox
- [x] Add interfaces and IPs to each gateway in Netbox
- [x] Add the domain to config_context `sites` in Netbox
- [X]  Add the domain to `wgkex.yaml` EDIT by @GoliathLabs: I've created a PR for this: https://github.com/freifunkMUC/site-ffm/pull/151
- [x] Test the rollout on one Gateway with `test=true` (salt-run jobs.lookup_jid 20211020104928365427)
- [x]  Roll it out on one gateway and try to connect with a node
- [x]  Roll it out on all gateways
- [X]  Add the new domain to meshviewer EDIT by @GoliathLabs: I've created a PR for this: https://github.com/freifunkMUC/meshviewer/pull/5

EDIT by @krombel; copy TODO-List to first comment to enable github to track progress

2021-10-16 21:38 UTC, goligo requested changes
next_node IP addresses need to be adapted to the new prefixes as well. 

I am not sure whether we should use "muenchen.freifunk.net" SSIDs for Augsburg, even if they run on our infrastructure. Can't we just use "augsburg.freifunk.net" instead?

2021-10-18 07:55 UTC, awlx commented
Until now every domain which runs under muenchen.freifunk.net gets their suffix. That's because of some reasons:
1. It's clear FFMUC runs this domain
2. No meshing with old nodes in the original domain
3. It's consistent with /gauting and /freising etc

2021-10-18 08:14 UTC, awlx requested changes

2021-10-18 08:14 UTC, awlx commented on domains/ffmuc_augsburg.conf
> +  next_node = {
Please fix the nextnode addresses as well

2021-10-18 08:18 UTC, GoliathLabs commented on domains/ffmuc_augsburg.conf
> +  next_node = {
Done

2021-10-18 08:20 UTC, awlx commented
For the admins @lqb, @goligo and @krombel that also means that we need to allocate those ranges in netbox and roll the changes out on the Gateways.

2021-10-18 08:30 UTC, awlx commented
Steps needed:
- [ ] Allocate IP ranges in Netbox
- [ ] Add interfaces and IPs to each gateway in Netbox
- [ ] Add the site to config_context `sites` in Netbox
- [ ]  Add the site to `wgkex.yaml`
- [ ] Test the rollout on one Gateway with `test=true`
- [ ]  Roll it out on one gateway and try to connect with a node
- [ ]  Roll it out on all gateways

2021-10-18 08:34 UTC, GoliathLabs commented
@awlx we also need to add the new domain to our meshviewer config

2021-10-18 08:38 UTC, awlx commented
@GoliathLabs the process would be even easier if `wgkex.yaml` and meshviewer config get autogenerated by salt. Maybe a good first salt PR for you.

2021-10-18 08:39 UTC, awlx approved these changes

2021-10-18 11:24 UTC, awlx commented
Even tho I approved this, it shouldn't be merged until all other steps are fulfilled.

2021-10-20 09:26 UTC, goligo approved these changes

2021-10-20 13:47 UTC, merged