Makefile: Keep output artifacts when rebuilding
freifunkMUC/site-ffm pull request #198
Opened 2022-10-03 20:15 UTC by grische

When doing a new build or a rebuild, all previous artifacts are deleted even if the new build fails. Replacing mv with rsync allows preserving previous artifacts.

2022-10-04 17:59 UTC, goligo reviewed
Honestly, I don't like this - just complicates things, if old build artifacts are kept. You can no longer distinguish, whether they are from the current or last build, whether they include your latest change or they don't.

If you want to keep old build output, make a local script to copy them somewhere else.

2022-10-04 19:49 UTC, grische commented
Each build has both a timestamp as well as it uses the git hash in its name. I don't see how you be struggling to distinguish new and old builds, when builds take always more than a few minutes.

2022-10-05 23:02 UTC, goligo requested changes
Seriously, I think this is wrong. I don't want to keep old build output. If you really want this, hide it behind a build option and keep the default as is.

2023-08-27 01:37 UTC, Djfe commented
in Aachen we use environment variables now and only have one output folder for Gluon instead
no mv or rsync needed. This way you have to to move outputfolders if you want to keep old builds.

we set
```
GLUON_SITEDIR := ..  # can only be set in makefile, we don't need to create a symbolic link anylonger
GLUON_OUTPUTDIR := $(GLUON_SITEDIR)/output  # we are setting this in our site.mk
```
https://gluon.readthedocs.io/en/latest/user/getting_started.html

also we have a different output folder, for when we build single devices now:
```
ifdef GLUON_DEVICES
    GLUON_OUTPUTDIR := $(GLUON_SITEDIR)/devices
endif
```

2023-11-01 13:57 UTC, GoliathLabs commented
> in Aachen we use environment variables now and only have one output folder for Gluon instead. no mv or rsync needed. This way you have to move outputfolders if you want to keep old builds.
> 
> we set
> 
> ```
> GLUON_SITEDIR := ..  # can only be set in makefile, we don't need to create a symbolic link anylonger
> GLUON_OUTPUTDIR := $(GLUON_SITEDIR)/output  # we are setting this in our site.mk
> ```
> 
> https://gluon.readthedocs.io/en/latest/user/getting_started.html
> 
> also we have a different output folder, for when we build single devices now:
> 
> ```
> ifdef GLUON_DEVICES
>     GLUON_OUTPUTDIR := $(GLUON_SITEDIR)/devices
> endif
> ```
> 
> (we stop output-clean, when GLUON_DEVICES is set)

@grische what do you think?

2026-01-03 19:07 UTC, closed without merging