Remove USB from EX3700/3800
freifunkMUC/site-ffm pull request #225
Opened 2022-12-19 12:28 UTC by maurerle

As this device does not have a lot of Flash left which softbricked one device for me, I would suggest to remove USB as this is not available for those devices anyways.

2022-12-19 13:35 UTC, awlx approved these changes

2022-12-19 13:36 UTC, GoliathLabs approved these changes

2022-12-19 13:37 UTC, GoliathLabs requested changes
Can you also run the script and change the site.mk file accordingly?

2023-01-02 21:45 UTC, maurerle commented
Sorry, I forgot about it - should be ready to merge

2023-01-02 21:51 UTC, GoliathLabs approved these changes

2023-01-02 21:52 UTC, GoliathLabs commented
@maurerle thanks for the work. Will wait until the CI checks completed successfully.

2023-01-03 10:15 UTC, merged