Use Github Bot for Action
freifunkMUC/site-ffm pull request #516
Opened 2024-11-03 14:18 UTC by T0biii

Use Github Bot for Action

ToDo

- [ ] Add new Bot (GitHub Apps) in Org Context
	- [ ] Set Name (This name is used for Commits and PR Geration)
	- [ ] Set Homepage URL (e.g. https://ffmuc.net)
	- [ ] Remove "Expire user authorization tokens"
	- [ ] Remove "Webhook Active"
	- [ ] Add Repository Permissions
		- [ ] Actions Read and Write
		- [ ] Contents Read and Write
		- [ ] Issues Read and Write
		- [ ] Metadata Read-only
		- [ ] Pull requests Read and Write
		- [ ] Workflows Read and Write
	- [ ] Only on this account (@freifunkmuc)
- [ ] After Creation of Bot
	- [ ] General Tab
		- [ ] save App ID for later
		- [ ] save Private keys -> Generate a private key -> for later
	- [ ] Install App Tab
		- [ ] select @freifunkMUC Install
		- [ ] Only select repositories (freifunkMUC/site-ffm)
- [ ] Actions secrets and vars
	- [ ] Add new Repository variables to Repo `APP_ID` -> previously saved
	- [ ] Add new Repository secrets to Repo `PRIVATE_KEY` -> previously saved

die ToDos um den Bot zu erstellen kann ich übernehmen dafür fehlen mir die Github Rechte.
Die Var sowie das Secret könnten wir theoretisch auch als Org Secrets setzen, falls wir den Bot auf mehreren Repos brauchen.

Für folgende Workflows könnten wir es noch verwenden:
- https://github.com/freifunkMUC/site-ffm/blob/f76df973af0be086217f32efc9d9c80b06f088fb/.github/workflows/backport.yml
- https://github.com/freifunkMUC/site-ffm/blob/f76df973af0be086217f32efc9d9c80b06f088fb/.github/workflows/update-targets.yml

2024-11-29 11:31 UTC, T0biii commented
Hey, @DasSkelett @GoliathLabs @awlx @krombel
wäre cool wenn einer von euch dafür Zeit hättet, die Steps sind eigentlich alle oben beschrieben
Bei fragen gerne an mich und/oder @grische zu gehen

2024-11-30 02:33 UTC, GoliathLabs commented
@T0biii ist angelegt. Ich habe die Secrets & Vars im Repo-Scope angelegt.

2024-12-02 09:40 UTC, grische requested changes

2024-12-02 09:40 UTC, grische commented on .github/workflows/shellcheck.yml
> +        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
I think we have agreed that we do not want to pin Github-owned actions to their version hash

2024-12-02 09:40 UTC, grische commented on .github/workflows/update-targets.yml
> -      - uses: actions/checkout@v4
dito

2024-12-02 09:49 UTC, T0biii commented on .github/workflows/shellcheck.yml
> +        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
i only aligned it with the other files:

https://github.com/freifunkMUC/site-ffm/blob/stable/.github/workflows/backport.yml#L18
https://github.com/freifunkMUC/site-ffm/blob/stable/.github/workflows/bump-modules.yml#L19

there it is also pinned

2024-12-02 10:13 UTC, grische commented on .github/workflows/shellcheck.yml
> +        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
IMHO we should unpin it everywhere

2024-12-02 10:14 UTC, T0biii commented on .github/workflows/shellcheck.yml
> +        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
then i go to unpin it

2024-12-02 11:30 UTC, grische approved these changes

2024-12-02 11:45 UTC, merged